# Generated by Django 4.2.20 on 2025-03-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='call_link',
            field=models.CharField(blank=True, help_text='Use tel:+1234567890 for phone calls', max_length=100),
        ),
    ]
