# Generated by Django 4.2.20 on 2025-03-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_remove_feature_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='icon_url',
            field=models.URLField(blank=True, help_text='Add the Heroicon image URL here'),
        ),
    ]
